"""
Bronze Layer Ingestion Pipeline

This module ingests raw Parquet streaming events generated by the event
generator and writes them to the Bronze Delta table. The Bronze layer
preserves the raw data while adding ingestion metadata required for
lineage, auditing, and downstream processing.

Responsibilities:
- Read raw Parquet files
- Add ingestion metadata
- Write data to the Bronze Delta table
- Preserve the original event data without business transformations
"""