from __future__ import annotations

# Canonical catalogs used by the data generator.
# These pools are intentionally broad so the generator can produce a large
# volume of varied records without repeating the same combinations too often.
CONTENT_CATALOG = {
	"action": (
		"movie_die_hard",
		"movie_mad_max_fury_road",
		"movie_john_wick",
		"movie_terminator_2_judgment_day",
		"movie_the_dark_knight",
		"movie_top_gun_maverick",
		"movie_mission_impossible_fallout",
		"movie_gladiator",
		"movie_the_matrix",
		"movie_the_bourne_identity",
		"movie_lethal_weapon",
		"movie_speed",
		"movie_aliens",
		"movie_the_raid",
		"movie_extraction",
		"movie_atomic_blonde",
		"movie_baby_driver",
		"movie_kill_bill",
		"movie_point_break",
		"movie_true_lies",
		"movie_face_off",
		"movie_casino_royale",
		"movie_skyfall",
		"movie_mission_impossible_ghost_protocol",
		"movie_the_equalizer",
	),
	"adventure": (
		"movie_indiana_jones_and_the_raiders_of_the_lost_ark",
		"movie_jurassic_park",
		"movie_jumanji_welcome_to_the_jungle",
		"movie_the_goonies",
		"movie_national_treasure",
		"movie_uncharted",
		"movie_the_princess_bride",
		"movie_journey_to_the_center_of_the_earth",
		"movie_kong_skull_island",
		"movie_the_hobbit_an_unexpected_journey",
		"movie_around_the_world_in_80_days",
		"movie_the_secret_life_of_walter_mitty",
		"movie_swiss_family_robinson",
		"movie_life_of_pi",
		"movie_into_the_wild",
		"movie_the_lost_city",
		"movie_the_mummy",
		"movie_anaconda",
		"movie_sahara",
		"movie_everest",
		"movie_romancing_the_stone",
		"movie_the_adventures_of_tintin",
		"movie_journey_2_the_mysterious_island",
		"movie_pirates_of_the_caribbean_the_curse_of_the_black_pearl",
		"movie_the_lord_of_the_rings_the_fellowship_of_the_ring",
	),
	"animation": (
		"movie_toy_story",
		"movie_inside_out",
		"movie_coco",
		"movie_frozen",
		"movie_moana",
		"movie_zootopia",
		"movie_up",
		"movie_ratatouille",
		"movie_wall_e",
		"movie_finding_nemo",
		"movie_finding_dory",
		"movie_the_incredibles",
		"movie_encanto",
		"movie_spider_man_into_the_spider_verse",
		"movie_puss_in_boots_the_last_wish",
		"movie_minions",
		"movie_kung_fu_panda",
		"movie_shrek",
		"movie_the_lego_movie",
		"movie_kikis_delivery_service",
		"movie_spirited_away",
		"movie_my_neighbor_totoro",
		"movie_how_to_train_your_dragon",
		"movie_coraline",
		"movie_raya_and_the_last_dragon",
	),
	"anime": (
		"show_naruto",
		"show_one_piece",
		"show_attack_on_titan",
		"show_death_note",
		"show_demon_slayer_kimetsu_no_yaiba",
		"show_fullmetal_alchemist_brotherhood",
		"show_cowboy_bebop",
		"show_neon_genesis_evangelion",
		"show_bleach",
		"show_hunter_x_hunter",
		"show_my_hero_academia",
		"show_jujutsu_kaisen",
		"show_dragon_ball_z",
		"show_vinland_saga",
		"show_code_geass",
		"show_berserk",
		"show_mob_psycho_100",
		"show_steins_gate",
		"show_spy_x_family",
		"show_tokyo_ghoul",
		"show_sword_art_online",
		"show_kaguya_sama_love_is_war",
		"show_clannad",
		"show_violet_evergarden",
		"show_black_clover",
	),
	"biography": (
		"movie_a_beautiful_mind",
		"movie_the_theory_of_everything",
		"movie_lincoln",
		"movie_hidden_figures",
		"movie_bohemian_rhapsody",
		"movie_rocketman",
		"movie_elvis",
		"movie_ford_v_ferrari",
		"movie_ray",
		"movie_walk_the_line",
		"movie_schindlers_list",
		"movie_catch_me_if_you_can",
		"movie_the_social_network",
		"movie_the_wolf_of_wall_street",
		"movie_erin_brockovich",
		"movie_gandhi",
		"movie_malcolm_x",
		"movie_the_imitation_game",
		"movie_the_pursuit_of_happyness",
		"movie_straight_outta_compton",
		"movie_selma",
		"movie_12_years_a_slave",
		"movie_judy",
		"movie_jobs",
		"movie_the_kings_speech",
	),
	"comedy": (
		"show_the_office",
		"show_parks_and_recreation",
		"show_friends",
		"show_brooklyn_nine_nine",
		"show_modern_family",
		"show_seinfeld",
		"show_arrested_development",
		"show_community",
		"show_ted_lasso",
		"show_the_good_place",
		"show_schitts_creek",
		"movie_superbad",
		"movie_step_brothers",
		"movie_anchorman",
		"movie_wedding_crashers",
		"movie_bridesmaids",
		"movie_mean_girls",
		"movie_groundhog_day",
		"movie_ghostbusters",
		"movie_clueless",
		"movie_ferris_buellers_day_off",
		"movie_the_hangover",
		"movie_the_big_lebowski",
		"movie_dumb_and_dumber",
		"movie_yes_man",
	),
	"crime": (
		"show_breaking_bad",
		"show_better_call_saul",
		"show_narcos",
		"show_ozark",
		"show_peaky_blinders",
		"show_the_sopranos",
		"show_the_wire",
		"show_dexter",
		"show_mindhunter",
		"show_fargo",
		"show_money_heist",
		"show_lupin",
		"movie_the_godfather",
		"movie_goodfellas",
		"movie_the_departed",
		"movie_se7en",
		"movie_sicario",
		"movie_heat",
		"movie_scarface",
		"movie_prisoners",
		"movie_inside_man",
		"movie_mystic_river",
		"movie_the_town",
		"movie_no_country_for_old_men",
		"show_line_of_duty",
	),
	"documentary": (
		"movie_planet_earth",
		"movie_blue_planet_ii",
		"movie_our_planet",
		"movie_the_last_dance",
		"movie_free_solo",
		"movie_amy",
		"movie_man_on_wire",
		"movie_blackfish",
		"movie_the_social_dilemma",
		"movie_tiger_king",
		"movie_making_a_murderer",
		"movie_the_staircase",
		"movie_thirteen",
		"movie_icarus",
		"movie_jiro_dreams_of_sushi",
		"movie_the_cove",
		"movie_citizenfour",
		"movie_an_inconvenient_truth",
		"movie_march_of_the_penguins",
		"movie_supersize_me",
		"movie_my_octopus_teacher",
		"movie_wont_you_be_my_neighbor",
		"movie_summer_of_soul",
		"movie_wild_wild_country",
		"movie_the_keepers",
	),
	"drama": (
		"movie_the_shawshank_redemption",
		"movie_forrest_gump",
		"movie_the_godfather_part_ii",
		"movie_parasite",
		"movie_fight_club",
		"movie_the_green_mile",
		"movie_titanic",
		"movie_joker",
		"movie_there_will_be_blood",
		"movie_la_la_land",
		"movie_manchester_by_the_sea",
		"movie_a_star_is_born",
		"movie_little_women",
		"movie_brokeback_mountain",
		"movie_whiplash",
		"movie_room",
		"movie_the_piano",
		"movie_marriage_story",
		"movie_moonlight",
		"movie_nomadland",
		"movie_belfast",
		"movie_spotlight",
		"movie_the_power_of_the_dog",
		"movie_the_help",
		"movie_her",
	),
	"family": (
		"movie_home_alone",
		"movie_paddington",
		"movie_paddington_2",
		"movie_the_parent_trap",
		"movie_matilda",
		"movie_annie",
		"movie_mary_poppins",
		"movie_charlie_and_the_chocolate_factory",
		"movie_willy_wonka_and_the_chocolate_factory",
		"movie_the_princess_diaries",
		"movie_cheaper_by_the_dozen",
		"movie_freaky_friday",
		"movie_lilo_and_stitch",
		"movie_the_santa_clause",
		"movie_holes",
		"movie_night_at_the_museum",
		"movie_stuart_little",
		"movie_babe",
		"movie_akeelah_and_the_bee",
		"movie_enchanted",
		"movie_the_neverending_story",
		"movie_elf",
		"movie_bee_movie",
		"movie_the_bfg",
		"movie_the_little_rascals",
	),
	"fantasy": (
		"movie_harry_potter_and_the_sorcerers_stone",
		"movie_harry_potter_and_the_chamber_of_secrets",
		"movie_harry_potter_and_the_prisoner_of_azkaban",
		"movie_the_lord_of_the_rings_the_two_towers",
		"movie_the_hobbit_the_battle_of_the_five_armies",
		"movie_the_lord_of_the_rings_the_return_of_the_king",
		"movie_the_hobbit_the_desolation_of_smaug",
		"show_game_of_thrones",
		"show_the_witcher",
		"show_shadow_and_bone",
		"show_his_dark_materials",
		"movie_the_chronicles_of_narnia_the_lion_the_witch_and_the_wardrobe",
		"movie_pans_labyrinth",
		"movie_stardust",
		"movie_the_dark_crystal",
		"show_the_sandman",
		"show_once_upon_a_time",
		"show_carnival_row",
		"show_merlin",
		"movie_doctor_strange",
		"movie_thor_ragnarok",
		"movie_willow",
		"movie_the_golden_compass",
		"movie_the_green_knight",
		"movie_eragon",
	),
	"history": (
		"show_downton_abbey",
		"show_the_crown",
		"show_vikings",
		"show_rome",
		"show_band_of_brothers",
		"show_chernobyl",
		"show_the_last_kingdom",
		"show_medici",
		"show_anne_with_an_e",
		"show_marco_polo",
		"show_the_tudors",
		"show_versailles",
		"show_boardwalk_empire",
		"show_turn_washingtons_spies",
		"show_john_adams",
		"show_the_pacific",
		"show_the_serpent_queen",
		"show_the_english_game",
		"show_1883",
		"show_1923",
		"show_the_man_in_the_high_castle",
		"movie_the_last_duel",
		"movie_braveheart",
		"movie_lawrence_of_arabia",
		"movie_ben_hur",
	),
	"horror": (
		"show_stranger_things",
		"show_the_haunting_of_hill_house",
		"show_the_haunting_of_bly_manor",
		"movie_the_conjuring",
		"movie_insidious",
		"movie_hereditary",
		"movie_midsommar",
		"movie_the_exorcist",
		"movie_a_nightmare_on_elm_street",
		"movie_friday_the_13th",
		"movie_halloween",
		"movie_scream",
		"movie_it",
		"movie_the_shining",
		"movie_get_out",
		"movie_us",
		"movie_a_quiet_place",
		"movie_the_ring",
		"movie_sinister",
		"movie_paranormal_activity",
		"movie_candyman",
		"movie_the_babadook",
		"movie_the_witch",
		"movie_train_to_busan",
		"movie_saw",
	),
	"musical": (
		"show_glee",
		"movie_high_school_musical",
		"show_hannah_montana",
		"show_empire",
		"show_mozart_in_the_jungle",
		"show_nashville",
		"show_vinyl",
		"show_the_get_down",
		"show_daisy_jones_and_the_six",
		"movie_sing_street",
		"movie_8_mile",
		"movie_purple_rain",
		"movie_yesterday",
		"movie_the_sound_of_music",
		"movie_dreamgirls",
		"movie_pitch_perfect",
		"movie_fame",
		"movie_chicago",
		"movie_west_side_story",
		"movie_mamma_mia",
		"movie_grease",
		"movie_hairspray",
		"movie_les_miserables",
		"movie_the_greatest_showman",
		"movie_school_of_rock",
	),
	"music": (
		"show_song_exploder",
		"show_tiny_desk_concerts",
		"show_behind_the_music",
		"show_unsung",
		"show_metalocalypse",
		"movie_20_feet_from_stardom",
		"movie_miss_americana",
		"movie_searching_for_sugar_man",
		"movie_the_last_waltz",
		"movie_wham",
		"movie_what_happened_miss_simone",
		"movie_rolling_thunder_revue",
		"movie_this_is_it",
		"movie_a_homecoming_a_film_by_beyonce",
		"movie_jennifer_lopez_halftime",
		"movie_the_blues_brothers",
		"movie_shine_a_light",
		"movie_gimme_shelter",
		"movie_pink_floyd_the_wall",
		"movie_control",
		"movie_amadeus",
		"movie_sid_and_nancy",
		"movie_walk_hard_the_dewey_cox_story",
		"movie_sing",
		"movie_once",
	),
	"mystery": (
		"show_sherlock",
		"show_only_murders_in_the_building",
		"show_true_detective",
		"show_broadchurch",
		"show_veronica_mars",
		"movie_knives_out",
		"movie_glass_onion",
		"movie_the_girl_with_the_dragon_tattoo",
		"movie_the_sixth_sense",
		"movie_gone_girl",
		"movie_gone_baby_gone",
		"movie_zodiac",
		"movie_shutter_island",
		"movie_brick",
		"movie_rear_window",
		"movie_the_girl_on_the_train",
		"movie_l_a_confidential",
		"movie_memento",
		"movie_enola_holmes",
		"movie_see_how_they_run",
		"show_murderville",
		"show_monk",
		"show_psych",
		"show_the_afterparty",
		"movie_murder_on_the_orient_express",
	),
	"romance": (
		"show_bridgerton",
		"movie_pride_and_prejudice",
		"movie_emma",
		"movie_sense_and_sensibility",
		"movie_notting_hill",
		"movie_the_notebook",
		"movie_before_sunrise",
		"movie_before_sunset",
		"movie_before_midnight",
		"movie_the_fault_in_our_stars",
		"movie_about_time",
		"movie_call_me_by_your_name",
		"movie_me_before_you",
		"movie_crazy_rich_asians",
		"movie_love_actually",
		"movie_ten_things_i_hate_about_you",
		"movie_to_all_the_boys_ive_loved_before",
		"movie_the_kissing_booth",
		"movie_purple_hearts",
		"movie_a_walk_to_remember",
		"movie_dear_john",
		"movie_safe_haven",
		"movie_when_harry_met_sally",
		"movie_the_time_travelers_wife",
		"movie_ghost",
	),
	"sci_fi": (
		"show_the_expanse",
		"show_westworld",
		"show_black_mirror",
		"show_dark",
		"show_severance",
		"show_foundation",
		"show_lost_in_space",
		"show_altered_carbon",
		"show_star_trek_the_next_generation",
		"movie_blade_runner_2049",
		"movie_dune",
		"movie_arrival",
		"movie_interstellar",
		"movie_2001_a_space_odyssey",
		"movie_ex_machina",
		"movie_star_wars_a_new_hope",
		"movie_moon",
		"movie_edge_of_tomorrow",
		"movie_minority_report",
		"movie_the_martian",
		"movie_avatar",
		"movie_guardians_of_the_galaxy",
		"movie_alita_battle_angel",
		"movie_ready_player_one",
		"show_firefly",
	),
	"sports": (
		"show_friday_night_lights",
		"show_all_american",
		"show_cobra_kai",
		"show_drive_to_survive",
		"show_the_last_dance",
		"show_sunderland_til_i_die",
		"movie_moneyball",
		"movie_rocky",
		"movie_creed",
		"movie_remember_the_titans",
		"movie_hoosiers",
		"movie_invictus",
		"movie_rush",
		"movie_the_fighter",
		"movie_the_blind_side",
		"movie_field_of_dreams",
		"movie_miracle",
		"movie_a_league_of_their_own",
		"movie_king_richard",
		"movie_the_wrestler",
		"movie_the_iron_claw",
		"movie_chariots_of_fire",
		"movie_coach_carter",
		"movie_any_given_sunday",
		"movie_space_jam",
	),
	"thriller": (
		"show_you",
		"show_bodyguard",
		"show_homeland",
		"show_killing_eve",
		"show_the_americans",
		"show_24",
		"movie_the_silence_of_the_lambs",
		"movie_black_swan",
		"movie_nocturnal_animals",
		"movie_the_invitation",
		"movie_phone_booth",
		"movie_run",
		"movie_panic_room",
		"movie_the_invisible_guest",
		"show_jack_ryan",
		"show_the_night_agent",
		"show_the_recruit",
		"movie_safe_house",
		"movie_red_sparrow",
		"movie_collateral",
		"movie_oldboy",
		"movie_hard_candy",
		"movie_fracture",
		"movie_side_effects",
		"movie_run_lola_run",
	),
	"war": (
		"movie_saving_private_ryan",
		"movie_1917",
		"movie_dunkirk",
		"movie_apocalypse_now",
		"movie_full_metal_jacket",
		"movie_platoon",
		"movie_the_hurt_locker",
		"movie_all_quiet_on_the_western_front",
		"movie_the_thin_red_line",
		"movie_hacksaw_ridge",
		"movie_letters_from_iwo_jima",
		"movie_fury",
		"movie_black_hawk_down",
		"movie_jojo_rabbit",
		"movie_inglourious_basterds",
		"movie_bridge_of_spies",
		"movie_das_boot",
		"movie_war_horse",
		"movie_flags_of_our_fathers",
		"show_generation_kill",
		"show_masters_of_the_air",
		"movie_pearl_harbor",
		"movie_midway",
		"movie_enemy_at_the_gates",
		"movie_come_and_see",
	),
	"western": (
		"show_yellowstone",
		"show_deadwood",
		"show_godless",
		"show_longmire",
		"show_hell_on_wheels",
		"movie_the_good_the_bad_and_the_ugly",
		"movie_unforgiven",
		"movie_true_grit",
		"movie_the_magnificent_seven",
		"movie_django_unchained",
		"movie_once_upon_a_time_in_the_west",
		"movie_3_10_to_yuma",
		"movie_tombstone",
		"movie_rio_bravo",
		"movie_stagecoach",
		"movie_the_searchers",
		"movie_bone_tomahawk",
		"movie_hostiles",
		"movie_open_range",
		"movie_the_assassination_of_jesse_james_by_the_coward_robert_ford",
		"movie_mccabe_and_mrs_miller",
		"movie_the_ballad_of_buster_scruggs",
		"movie_the_hateful_eight",
		"movie_silverado",
		"movie_appaloosa",
	),
}

CONTENT_CATEGORIES = tuple(CONTENT_CATALOG.keys())
CONTENT_IDS = tuple(content_id for ids in CONTENT_CATALOG.values() for content_id in ids)

# Backward-compatible default content identifier for existing code paths.
CONTENT_ID = CONTENT_IDS[0]

# Reusable categorical values for streaming events.
EVENT_TYPE = "playback_started"
DEVICE = "smart_tv"
COUNTRY = "US"

EVENT_TYPES = (
	"audio_track_changed", "bitrate_changed", "buffering_ended", "buffering_started",
	"download_completed", "download_failed", "download_started", "fullscreen_entered",
	"fullscreen_exited", "loading_ended", "loading_started", "manifest_failed",
	"manifest_loaded", "network_error", "playback_completed", "playback_error",
	"playback_paused", "playback_resumed", "playback_seeked", "playback_started",
	"playback_stopped", "profile_switched", "quality_changed", "recommendation_impression",
	"search_completed", "search_started", "seek_backward", "seek_forward",
	"subtitle_disabled", "subtitle_enabled",
)

DEVICES = (
	"android_phone", "android_tablet", "android_tv", "apple_tv", "car_display",
	"chromecast", "connected_tv", "desktop", "external_display", "fire_tv",
	"gaming_console", "google_tv", "ipad", "iphone", "laptop", "macbook",
	"mobile", "nintendo_switch", "playstation", "portable_media_player",
	"projector", "roku", "set_top_box", "smart_display", "smart_speaker",
	"smart_tv", "smartphone", "streaming_stick", "tablet", "web_app",
	"web_browser", "windows_pc", "xbox",
)

COUNTRIES = (
	"AD", "AE", "AF", "AG", "AL", "AM", "AO", "AR",
	"AT", "AU", "AZ", "BA", "BB", "BD", "BE", "BF",
	"BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS",
	"BT", "BW", "BY", "BZ", "CA", "CD", "CF", "CG",
	"CH", "CI", "CL", "CM", "CO", "CR", "CU", "CV",
	"CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ",
	"EC", "EE", "EG", "ER", "ES", "ET", "FI", "FJ",
	"FM", "FR", "GA", "GB", "GD", "GE", "GH", "GM",
	"GN", "GQ", "GR", "GT", "GW", "GY", "HK", "HN",
	"HR", "HT", "HU", "ID", "IE", "IL", "IN", "IQ",
	"IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH",
	"KI", "KM", "KN", "KR", "KW", "KZ", "LA", "LB",
	"LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV",
	"LY", "MA", "MC", "MD", "ME", "MG", "MH", "MK",
	"ML", "MM", "MN", "MR", "MT", "MU", "MV", "MW",
	"MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL",
	"NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG",
	"PH", "PK", "PL", "PR", "PT", "PW", "PY", "QA",
	"RO", "RS", "RW", "SB", "SC", "SD", "SE", "SG",
	"SI", "SK", "SL", "SM", "SN", "SR", "SS", "ST",
	"SV", "SZ", "TD", "TG", "TH", "TJ", "TL", "TM",
	"TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA",
	"UG", "US", "UY", "UZ", "VA", "VC", "VE", "VN",
	"VU", "WS", "YE", "ZA", "ZM", "ZW",
)

__all__ = [
	"CONTENT_CATALOG",
	"CONTENT_CATEGORIES",
	"CONTENT_IDS",
	"CONTENT_ID",
	"EVENT_TYPE",
	"DEVICE",
	"COUNTRY",
	"EVENT_TYPES",
	"DEVICES",
	"COUNTRIES",
]
